language: go
sudo: false

go:
  - 1.11.x
  - master

install:
  - go get github.com/zeebo/bencode
  - go get github.com/gojp/goreportcard/cmd/goreportcard-cli
  - go get github.com/stretchr/testify/assert

script:
  - chmod +x ./build.sh
  - ./build.sh
  - go build main.go
