version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/concurrency-8

    steps:
      - checkout
      - run : sudo apt-get update
      - run : go get github.com/zeebo/bencode
      - run : go get github.com/alecthomas/gometalinter
      - run : go get github.com/gojp/goreportcard/cmd/goreportcard-cli
      - run : go get github.com/stretchr/testify/assert
      - run : chmod +x ./build.sh
      - run : ./build.sh
      - run : go build main.go